# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
    ]
