# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redir', '0003_auto_20181110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
